export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_FROM_PROJECT = 'DELETE_EMPLOYEE_FROM_PROJECT';